### ISSUE TITLE
添加网站报500错误

### ISSUE THREAD

**Issue by jxdjohn** [meimz/mbt#1]
你好，首先感谢你的SDK，它很有用。
我是个技术小白，在用你的SDK添加网站的时候提示如下
`johndeMBP:Downloads john$ python3 mBt.py 
Traceback (most recent call last):
  File "mBt.py", line 634, in <module>
    r_data_addsite = my_api.WebAddSite(webname,path,type_id,type,version,port,ps,ftp,ftp_username,ftp_password,sql,coding,datauser,datapassword)
  File "mBt.py", line 152, in WebAddSite
    return self._getData(url, p_data)
  File "mBt.py", line 40, in _getData
    result = self.__http_post_cookie(url, p_data)
  File "mBt.py", line 606, in __http_post_cookie
    response = opener.open(req,timeout = timeout)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 500: INTERNAL SERVER ERROR
`
本地python版本
`johndeMBP:Downloads john$ python3 -V
Python 3.7.0
`
宝塔版本：6.9.8
尝试了其他操作，例如查LOG记录，是可以正常的.
大神能否有空指导下？

**Comment by Bob-Yuan** [comment]
> 你好，首先感谢你的SDK，它很有用。
> 我是个技术小白，在用你的SDK添加网站的时候提示如下
> `johndeMBP:Downloads john$ python3 mBt.py Traceback (most recent call last): File "mBt.py", line 634, in <module> r_data_addsite = my_api.WebAddSite(webname,path,type_id,type,version,port,ps,ftp,ftp_username,ftp_password,sql,coding,datauser,datapassword) File "mBt.py", line 152, in WebAddSite return self._getData(url, p_data) File "mBt.py", line 40, in _getData result = self.__http_post_cookie(url, p_data) File "mBt.py", line 606, in __http_post_cookie response = opener.open(req,timeout = timeout) File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 531, in open response = meth(req, response) File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 641, in http_response 'http', request, response, code, msg, hdrs) File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 569, in error return self._call_chain(*args) File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 503, in _call_chain result = func(*args) File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 649, in http_error_default raise HTTPError(req.full_url, code, msg, hdrs, fp) urllib.error.HTTPError: HTTP Error 500: INTERNAL SERVER ERROR `
> 本地python版本
> `johndeMBP:Downloads john$ python3 -V Python 3.7.0 `
> 宝塔版本：6.9.8
> 尝试了其他操作，例如查LOG记录，是可以正常的.
> 大神能否有空指导下？

p_data['webname']后面的字典要用双引号，就像这样：
p_data['webname'] = "{'domain': 'test.com', 'domainlist': ['www.test.com'], 'count': 0}"

**Comment by Bob-Yuan** [comment]
> 你好，首先感谢你的SDK，它很有用。
> 我是个技术小白，在用你的SDK添加网站的时候提示如下
> `johndeMBP:Downloads john$ python3 mBt.py Traceback (most recent call last): File "mBt.py", line 634, in <module> r_data_addsite = my_api.WebAddSite(webname,path,type_id,type,version,port,ps,ftp,ftp_username,ftp_password,sql,coding,datauser,datapassword) File "mBt.py", line 152, in WebAddSite return self._getData(url, p_data) File "mBt.py", line 40, in _getData result = self.__http_post_cookie(url, p_data) File "mBt.py", line 606, in __http_post_cookie response = opener.open(req,timeout = timeout) File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 531, in open response = meth(req, response) File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 641, in http_response 'http', request, response, code, msg, hdrs) File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 569, in error return self._call_chain(*args) File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 503, in _call_chain result = func(*args) File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 649, in http_error_default raise HTTPError(req.full_url, code, msg, hdrs, fp) urllib.error.HTTPError: HTTP Error 500: INTERNAL SERVER ERROR `
> 本地python版本
> `johndeMBP:Downloads john$ python3 -V Python 3.7.0 `
> 宝塔版本：6.9.8
> 尝试了其他操作，例如查LOG记录，是可以正常的.
> 大神能否有空指导下？
请注意一下post的数据格式，比如我的：
        p_data['webname'] = json.dumps({'domain': 'abc.com', 'domainlist': ['www.abc.com'], 'count': 0})
        p_data['path'] = '/www/wwwroot/yb.com'
        p_data['type_id'] = '0'
        p_data['type'] = 'PHP'
        p_data['version'] = '74'
        p_data['port'] = '80'
        p_data['ps'] = 'test'
        p_data['ftp'] = "False"
        p_data['ftp_username'] = 'testtest'
        p_data['ftp_password'] = 'testtest'
        p_data['sql'] = "False"
        p_data['codeing'] = 'utf8'
        p_data['datauser'] = 'testtest'
        p_data['datapassword'] = 'testtesttesttest'
